import { FileRecord } from '../models/CatalogModel';

export const MOCK_FILES: FileRecord[] = [
    {
        id: 'f-001',
        name: 'Q4_2024_Financial_Report.pdf',
        fileType: 'pdf',
        storagePath: 'abfss://bronze@catalogiqsa.dfs.core.windows.net/finance/reports/Q4_2024_Financial_Report.pdf',
        description: 'Annual financial report covering Q4 2024 earnings, revenue breakdown, and projections.',
        tags: ['finance', 'quarterly', '2024', 'report'],
        sizeBytes: 2_450_000,
        lastModified: '2024-12-31T18:00:00Z',
        source: 'Lakehouse/bronze',
        owner: 'finance-team',
    },
    {
        id: 'f-002',
        name: 'customer_feedback_jan2025.json',
        fileType: 'json',
        storagePath: 'abfss://bronze@catalogiqsa.dfs.core.windows.net/crm/feedback/customer_feedback_jan2025.json',
        description: 'Structured customer feedback collected via survey in January 2025. Contains ratings, comments, and NPS scores.',
        tags: ['crm', 'feedback', '2025', 'nps'],
        sizeBytes: 820_000,
        lastModified: '2025-02-01T09:15:00Z',
        source: 'Lakehouse/bronze',
        owner: 'cx-team',
    },
    {
        id: 'f-003',
        name: 'call_center_recording_2025_01_15.mp3',
        fileType: 'audio',
        storagePath: 'abfss://audio@catalogiqsa.dfs.core.windows.net/callcenter/2025/01/call_center_recording_2025_01_15.mp3',
        description: 'Call center recording from January 15 2025. Contains customer support interaction regarding billing issue.',
        tags: ['audio', 'call-center', 'billing', '2025'],
        sizeBytes: 15_600_000,
        lastModified: '2025-01-15T14:30:00Z',
        source: 'Lakehouse/audio',
        owner: 'ops-team',
    },
    {
        id: 'f-004',
        name: 'product_catalog_v3.csv',
        fileType: 'csv',
        storagePath: 'abfss://bronze@catalogiqsa.dfs.core.windows.net/products/product_catalog_v3.csv',
        description: 'Full product catalog including SKUs, descriptions, pricing, and inventory levels. Version 3 includes new electronics category.',
        tags: ['products', 'catalog', 'inventory', 'pricing'],
        sizeBytes: 5_200_000,
        lastModified: '2025-01-20T11:00:00Z',
        source: 'Lakehouse/bronze',
        owner: 'supply-chain',
    },
    {
        id: 'f-005',
        name: 'employee_handbook_2025.pdf',
        fileType: 'pdf',
        storagePath: 'abfss://bronze@catalogiqsa.dfs.core.windows.net/hr/docs/employee_handbook_2025.pdf',
        description: 'Updated employee handbook for 2025. Includes new remote work policy, benefits guide, and code of conduct.',
        tags: ['hr', 'policy', 'handbook', '2025'],
        sizeBytes: 3_100_000,
        lastModified: '2025-01-02T08:00:00Z',
        source: 'Lakehouse/bronze',
        owner: 'hr-team',
    },
    {
        id: 'f-006',
        name: 'iot_sensor_readings_feb2025.json',
        fileType: 'json',
        storagePath: 'abfss://raw@catalogiqsa.dfs.core.windows.net/iot/sensors/iot_sensor_readings_feb2025.json',
        description: 'IoT sensor telemetry data for February 2025. Temperature, pressure, and humidity readings from factory floor sensors.',
        tags: ['iot', 'telemetry', 'sensors', '2025', 'factory'],
        sizeBytes: 42_000_000,
        lastModified: '2025-02-10T23:59:00Z',
        source: 'CosmosDB',
        owner: 'iot-team',
    },
    {
        id: 'f-007',
        name: 'marketing_campaign_assets.zip',
        fileType: 'other',
        storagePath: 'abfss://bronze@catalogiqsa.dfs.core.windows.net/marketing/campaigns/marketing_campaign_assets.zip',
        description: 'Compressed archive of marketing assets for Spring 2025 campaign including banners, logos, and copy.',
        tags: ['marketing', 'campaign', 'assets', '2025'],
        sizeBytes: 89_000_000,
        lastModified: '2025-02-14T16:00:00Z',
        source: 'Lakehouse/bronze',
        owner: 'marketing-team',
    },
    {
        id: 'f-008',
        name: 'contract_nda_acme_corp.pdf',
        fileType: 'pdf',
        storagePath: 'abfss://secure@catalogiqsa.dfs.core.windows.net/legal/contracts/contract_nda_acme_corp.pdf',
        description: 'Non-disclosure agreement with Acme Corp signed February 2025. Valid for 3 years.',
        tags: ['legal', 'contract', 'nda', 'acme'],
        sizeBytes: 890_000,
        lastModified: '2025-02-05T10:00:00Z',
        source: 'Lakehouse/secure',
        owner: 'legal-team',
    },
    {
        id: 'f-009',
        name: 'training_video_databricks_intro.mp4',
        fileType: 'video',
        storagePath: 'abfss://training@catalogiqsa.dfs.core.windows.net/videos/training_video_databricks_intro.mp4',
        description: 'Internal training video introducing Databricks and Azure Data services to new data engineers.',
        tags: ['training', 'databricks', 'onboarding', 'video'],
        sizeBytes: 520_000_000,
        lastModified: '2024-11-15T09:00:00Z',
        source: 'Lakehouse/training',
        owner: 'data-platform',
    },
    {
        id: 'f-010',
        name: 'sales_forecast_model_output.csv',
        fileType: 'csv',
        storagePath: 'abfss://gold@catalogiqsa.dfs.core.windows.net/forecasting/sales_forecast_model_output.csv',
        description: 'ML model output for sales forecasting Q1 2025. Predictions by region, product line, and sales rep.',
        tags: ['ml', 'forecast', 'sales', '2025', 'predictions'],
        sizeBytes: 1_200_000,
        lastModified: '2025-01-30T12:00:00Z',
        source: 'Lakehouse/gold',
        owner: 'data-science',
    },
];
